version: '3.8'

services:
  load-balancer-app:
    build: ./
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - monitoring
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

networks:
  monitoring:
