// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: servers.sql

package database

import (
	"context"
)

const getServers = `-- name: GetServers :many
select id, server_url from servers
`

func (q *Queries) GetServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, getServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(&i.ID, &i.ServerUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
